.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. cryptotalkcoin_qt test_cryptotalkcoin_qt
clean: FORCE
	$(MAKE) -C .. cryptotalkcoin_qt_clean test_cryptotalkcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_cryptotalkcoin_qt_check
cryptotalkcoin-qt cryptotalkcoin-qt.exe: FORCE
	 $(MAKE) -C .. cryptotalkcoin_qt
